### ISSUE TITLE
Lifter Request: Enter USPA meet

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#582] opened 2018-01-16 19:31 UTC
http://www.uspa.net/uspaform/download.php?q=Zm9ybV9pZD0yMDE3MCZpZD0xMDc5JmVsPWVsZW1lbnRfMSZoYXNoPTc3MDliODA1NmVjNjI2NGE5ODgxNWViMGIwNjBlZDY4

Marlow King is the lifter. Her instagram is @marlowjess

**Comment by sstangl** [comment] 2018-01-16 19:33
Duplicate of #580.

**Closed by sstangl** 2018-01-16 19:33 UTC
