### ISSUE TITLE
Wilks Issue with Lifter Joshua Rodda

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#975] opened 2018-03-20 23:25 UTC
Joshua Rodda lifted in the XPC Finals and claims that his wilks is wrong. He is in the 308 weight class but weighed in at 282.6 lbs. he claims. I have no proof of that sadly. When looking at the XPC results they did not report bodyweight so we apparently just went off of their reported weight class. They did report him of having a coefficient of 1009.792. Here is the link to the results on their site http://www.xpcpowerlifting.com/2018-xpc-finals-results/ . He also states that the meet was on March 3rd, not March 2nd.

**Comment by sstangl** [comment] 2018-03-20 23:45
The XPC did report bodyweight, but they did so in CSV files that were emailed to us. They reported his bodyweight as `286.2`, not as `282.6`, so if there is an error, it is on the XPC side.

Friday is correct because we lumped all the XPC events into a single XPC meet, and that meet was Friday the 2nd through Sunday the 4th.

**Comment by sstangl** [comment] 2018-03-20 23:46
I emailed Nic to ask for clarification on the bodyweight.

**Comment by sstangl** [comment] 2018-03-21 00:25
Nic emailed back a photo of his weigh-in card, clearly showing `286.2`, so he is mistaken.

Weigh-in: https://i.imgur.com/vMRGnqw.jpg

Resolving invalid. Please let him know.

**Closed by sstangl** 2018-03-21 00:25 UTC
Labels: data error, lifter-request

**Comment by TrystanOakley** [comment] 2018-03-21 03:45
So I suppose that the body weight would still be incorrect on our site then and need to be changed correct?

**Comment by sstangl** [comment] 2018-03-21 03:56
No, we have always had him as `286.2`, which the XPC confirmed as correct.

**Comment by TrystanOakley** [comment] 2018-03-21 22:54
Oh my bad
